create table if not exists environments (
  id varchar(32) primary key,
  name varchar(64) not null,
  kind varchar(16) not null,
  region varchar(64) not null,
  cluster_label varchar(64) not null,
  summary varchar(255) not null,
  broker_url varchar(255) not null,
  admin_url varchar(255) not null,
  auth_mode varchar(32) not null,
  credential_reference varchar(255),
  tls_enabled boolean not null default false,
  status varchar(16) not null,
  sync_status varchar(32) not null default 'NOT_SYNCED',
  sync_message varchar(255),
  last_synced_at timestamp,
  last_test_status varchar(32) not null default 'NOT_TESTED',
  last_test_message varchar(255),
  last_tested_at timestamp,
  deleted_at timestamp,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create table if not exists environment_snapshots (
  environment_id varchar(32) primary key references environments(id),
  health_status varchar(16) not null,
  health_message varchar(255) not null,
  pulsar_version varchar(32) not null,
  broker_url varchar(255) not null,
  admin_url varchar(255) not null,
  tenant_count integer not null default 0,
  namespace_count integer not null default 0,
  topic_count integer not null default 0,
  tenants_json text not null,
  namespaces_json text not null,
  topics_json text not null,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create table if not exists jobs (
  id varchar(64) primary key,
  type varchar(32) not null,
  environment_id varchar(32) not null references environments(id),
  status varchar(16) not null,
  parameters text not null default '{}',
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create table if not exists job_events (
  id bigint generated by default as identity primary key,
  job_id varchar(64) not null references jobs(id),
  event_type varchar(32) not null,
  details text not null default '{}',
  created_at timestamp not null default current_timestamp
);
