package com.pulsaradmin.worker;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.Timestamp;
import java.time.Instant;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;

@SpringBootTest
@TestPropertySource(properties = {
    "spring.datasource.url=jdbc:h2:mem:workerdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
    "spring.datasource.username=sa",
    "spring.datasource.password=",
    "worker.jobs.scheduling-enabled=false"
})
class ReplayCopyJobWorkerTest {
  @Autowired
  private JdbcTemplate jdbcTemplate;

  @Autowired
  private WorkerJobRepository workerJobRepository;

  @Autowired
  private ReplayCopyJobWorker replayCopyJobWorker;

  @BeforeEach
  void setUpSchema() {
    jdbcTemplate.execute("drop table if exists job_events");
    jdbcTemplate.execute("drop table if exists jobs");
    jdbcTemplate.execute("""
        create table jobs (
          id varchar(64) primary key,
          type varchar(32) not null,
          environment_id varchar(32) not null,
          status varchar(16) not null,
          parameters text not null,
          created_at timestamp not null,
          updated_at timestamp not null
        )
        """);
    jdbcTemplate.execute("""
        create table job_events (
          id bigint generated by default as identity primary key,
          job_id varchar(64) not null,
          event_type varchar(32) not null,
          details text not null,
          created_at timestamp not null
        )
        """);
  }

  @Test
  void shouldProcessQueuedCopyJob() {
    Instant now = Instant.parse("2026-03-17T19:00:00Z");
    jdbcTemplate.update("""
        insert into jobs (id, type, environment_id, status, parameters, created_at, updated_at)
        values (?, ?, ?, ?, ?, ?, ?)
        """,
        "job-test-1",
        "COPY",
        "prod",
        "QUEUED",
        """
        {"topicName":"persistent://acme/orders/payment-events","subscriptionName":"payment-settlement","destinationTopicName":"persistent://acme/dev/replay-lab","messageLimit":100,"messagesPerSecond":50,"filterText":"payment-10412","reason":"test","statusMessage":"Queued for worker pickup.","matchedMessages":0,"publishedMessages":0}
        """,
        Timestamp.from(now),
        Timestamp.from(now));

    replayCopyJobWorker.processQueuedJobs();

    var job = workerJobRepository.findById("job-test-1").orElseThrow();
    Integer eventCount = jdbcTemplate.queryForObject(
        "select count(*) from job_events where job_id = ?",
        Integer.class,
        "job-test-1");

    assertThat(job.status().name()).isEqualTo("COMPLETED");
    assertThat(job.parameters().get("publishedMessages")).isEqualTo(36);
    assertThat(eventCount).isEqualTo(2);
  }

  @TestConfiguration
  static class TestConfig {
    @Bean
    ReplayCopyJobWorker replayCopyJobWorker(
        WorkerJobRepository workerJobRepository,
        WorkerJobEventRepository workerJobEventRepository) {
      return new ReplayCopyJobWorker(workerJobRepository, workerJobEventRepository, 5);
    }
  }
}
