package com.pulsaradmin.worker;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.Timestamp;
import java.time.Instant;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;

@SpringBootTest
@TestPropertySource(properties = {
    "spring.datasource.url=jdbc:h2:mem:workerdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
    "spring.datasource.username=sa",
    "spring.datasource.password=",
    "spring.task.scheduling.enabled=false",
    "worker.jobs.scheduling-enabled=false"
})
class ReplayCopyJobWorkerTest {
  @Autowired
  private JdbcTemplate jdbcTemplate;

  @Autowired
  private WorkerJobRepository workerJobRepository;

  @Autowired
  private WorkerJobEventRepository workerJobEventRepository;

  @Autowired
  private WorkerEnvironmentRepository workerEnvironmentRepository;

  @Autowired
  private WorkerReplayCopyJobCriteriaRepository workerReplayCopyJobCriteriaRepository;

  @Autowired
  private ObjectMapper objectMapper;

  @BeforeEach
  void setUpSchema() {
    jdbcTemplate.execute("drop table if exists job_events");
    jdbcTemplate.execute("drop table if exists replay_copy_job_search_results");
    jdbcTemplate.execute("drop table if exists replay_copy_job_criteria");
    jdbcTemplate.execute("drop table if exists replay_copy_job_filters");
    jdbcTemplate.execute("drop table if exists jobs");
    jdbcTemplate.execute("drop table if exists environments");
    jdbcTemplate.execute("""
        create table environments (
          id varchar(32) primary key,
          broker_url varchar(255) not null,
          admin_url varchar(255) not null,
          auth_mode varchar(32) not null,
          credential_reference varchar(255),
          tls_enabled boolean not null default false,
          deleted_at timestamp
        )
        """);
    jdbcTemplate.execute("""
        create table jobs (
          id varchar(64) primary key,
          type varchar(32) not null,
          environment_id varchar(32) not null,
          status varchar(16) not null,
          parameters text not null,
          created_at timestamp not null,
          updated_at timestamp not null
        )
        """);
    jdbcTemplate.execute("""
        create table job_events (
          id bigint generated by default as identity primary key,
          job_id varchar(64) not null,
          event_type varchar(32) not null,
          details text not null,
          created_at timestamp not null
        )
        """);
    jdbcTemplate.execute("""
        create table replay_copy_job_criteria (
          id bigint generated by default as identity primary key,
          job_id varchar(64) not null,
          row_index int not null,
          field_name varchar(128) not null,
          field_value varchar(512) not null,
          created_at timestamp not null default current_timestamp
        )
        """);
    jdbcTemplate.execute("""
        create table replay_copy_job_filters (
          id bigint generated by default as identity primary key,
          job_id varchar(64) not null,
          filter_value varchar(512) not null,
          created_at timestamp not null default current_timestamp
        )
        """);
    jdbcTemplate.execute("""
        create table replay_copy_job_search_results (
          id bigint generated by default as identity primary key,
          job_id varchar(64) not null,
          message_id varchar(255),
          message_key varchar(255),
          properties_json text not null,
          payload text not null,
          matched_field_value varchar(1024),
          created_at timestamp not null default current_timestamp
        )
        """);
    jdbcTemplate.update("""
        insert into environments (id, broker_url, admin_url, auth_mode, credential_reference, tls_enabled, deleted_at)
        values (?, ?, ?, ?, ?, ?, ?)
        """, "prod", "mock://local", "http://localhost:8081", "none", null, false, null);
  }

  @Test
  void shouldProcessQueuedCopyJob() {
    ReplayCopyJobWorker replayCopyJobWorker = new ReplayCopyJobWorker(
        workerJobRepository,
        workerJobEventRepository,
        workerEnvironmentRepository,
        workerReplayCopyJobCriteriaRepository,
        new WorkerReplayCopyJobSearchResultRepository(jdbcTemplate, objectMapper),
        objectMapper,
        5,
        500,
        5,
        25,
        2,
        1000);
    Instant now = Instant.parse("2026-03-17T19:00:00Z");
    jdbcTemplate.update("""
        insert into jobs (id, type, environment_id, status, parameters, created_at, updated_at)
        values (?, ?, ?, ?, ?, ?, ?)
        """,
        "job-test-1",
        "COPY",
        "prod",
        "QUEUED",
        """
        {"topicName":"persistent://acme/orders/payment-events","subscriptionName":"payment-settlement","destinationTopicName":"persistent://acme/dev/replay-lab","messageLimit":100,"messagesPerSecond":50,"filterText":"payment-10412","reason":"test","statusMessage":"Queued for worker pickup.","matchedMessages":0,"publishedMessages":0}
        """,
        Timestamp.from(now),
        Timestamp.from(now));

    replayCopyJobWorker.processQueuedJobs();

    var job = workerJobRepository.findById("job-test-1").orElseThrow();
    Integer eventCount = jdbcTemplate.queryForObject(
        "select count(*) from job_events where job_id = ?",
        Integer.class,
        "job-test-1");

    assertThat(job.status().name()).isEqualTo("COMPLETED");
    assertThat(job.parameters().get("publishedMessages")).isEqualTo(12);
    assertThat(eventCount).isEqualTo(2);
  }
}
